CREATE DATABASE MIBASE;
use MIBASE;
CREATE TABLE USUARIO (
    CI INT(10) UNSIGNED PRIMARY KEY,
    USUARIO VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(15) NOT NULL,
    ROL VARCHAR(20) NOT NULL,
    CARRERA VARCHAR(10) NOT NULL
    APARIENCIA VARCHAR(20) NOT NULL
    
);
CREATE TABLE PERSONA(
    CI INT(10) UNSIGNED PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    FECHA_NACIMIENTO DATE,
    DEPARTAMENTO int(2) NOT NULL
);
CREATE TABLE NOTAS(
    CI INT(10) UNSIGNED PRIMARY KEY,
    SIGLA VARCHAR(15) NOT NULL,
    Nota1 FLOAT(4),
    Nota2 FLOAT(4),
    Nota3 FLOAT(4),
    NotaFinal FLOAT(4)
);